name: "Upload artefact"

on:
  push:
    branches:
      - master

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Archive production artefact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: lara.py
